#!/bin/bash
echo '             _____   _       ___             '
echo '            |__ __| | |___  | _ |            '
echo '              | |   |  _  | | __|            '
echo '              |_|   |_| |_| |___|            '
echo '         ____                                '
echo '        |  __|   ____  ___  ___  ____        '
echo '        |  | __ | ___|| _ || _ || __ |       '
echo '        |  |_| || |   | __|| __|| || |       '
echo '        |______||_|   |___||___||_||_|       '
echo '  ________                                    '
echo ' |        | ______  ____  _      _  ____  ___ '
echo ' |  |  |  ||  _   ||  __|| |___ | || __ || __|'
echo ' |  |  |  || |_|  || |__ |  _  || || || || __|'
echo ' |__|__|__||____|_||____||_| |_||_||_||_||___|'
echo
echo ' 	       Compile Script by YoshiShaPow        '
echo

# Tuneables
defconfig=tgm_bacon_defconfig
jobs="8"
toolchain="/home/yoshishapow/kernels/toolchains/cortex_a15/bin/arm-eabi-"
kerneltype="zImage"
output="~/kernels/out/bacon"
TGM_version="~(≧０≦)~TGM-v1"

# Let's start
export LOCALVERSION=$TGM_version
export ARCH=arm
export SUBARCH=arm
export CROSS_COMPILE=$toolchain

echo

while read -p "Do you want to make clean (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		make clean && make mrproper
		echo
		echo "Done"
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

echo

while read -p "Do you want to make defconfig (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		make $defconfig
		echo
		echo "Done"
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

echo

DATE_START=$(date +"%s")

while read -p "Do you want to build (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		
		make -j$jobs
		echo
		echo "Done"
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

echo

if [[ -f $output/zImage ]]
	then
		echo 'TGM is Done'
		echo 'Removing old img'
		rm -f ../out/boot*
		./bacon_ramdisk/dtbToolCM -2 -o ../bacon_ramdisk/split_img/boot.img-dtb -s 2048 -p ../tgm_bacon/scripts/dtc/ ../tgm_bacon/arch/arm/boot/
		cp arch/arm/boot/zImage ../bacon_ramdisk/split_img/boot.img-zImage
		cd ../bacon_ramdisk/
		./repackimg.sh
		cp ./image-new.img ../out/boot.img
	else
		echo 'Better fix something up! Build failed'
fi
DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
echo "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."

