#!/bin/bash
echo '             _____   _       ___             '
echo '            |__ __| | |___  | _ |            '
echo '              | |   |  _  | | __|            '
echo '              |_|   |_| |_| |___|            '
echo '         ____                                '
echo '        |  __|   ____  ___  ___  ____        '
echo '        |  | __ | ___|| _ || _ || __ |       '
echo '        |  |_| || |   | __|| __|| || |       '
echo '        |______||_|   |___||___||_||_|       '
echo '  ________                                    '
echo ' |        | ______  ____  _      _  ____  ___ '
echo ' |  |  |  ||  _   ||  __|| |___ | || __ || __|'
echo ' |  |  |  || |_|  || |__ |  _  || || || || __|'
echo ' |__|__|__||____|_||____||_| |_||_||_||_||___|'
echo
echo ' 	    Compile Script by YoshiShaPow        '

# Tuneables
buildname="TGM-Lollipop-v1.0.0"
defconfig="tgm_bacon_defconfig"
jobs="8"
toolchain="/home/yoshishapow/kernels/toolchains/cortex_a15/bin/arm-cortex_a15-linux-gnueabihf-"
kerneltype="zImage"
output="../out/bacon"
ps=2048
base=0x00000000
ramdisk_offset=0x02000000
tags_offset=0x01e00000
cmdline="console=ttyHSL0,115200,n8 androidboot.hardware=bacon user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.selinux=permissive"

# Let's start
export ARCH=arm
export SUBARCH=arm
export CROSS_COMPILE=$toolchain

echo

while read -p "Do you want to make clean (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		make clean && make mrproper
		rm -rf ozip/boot.img
		rm -rf arch/arm/boot/"$kerneltype"
		mkdir -p ozip/system/lib/modules
		rm -rf out
		mkdir out
		echo
		echo "Done"
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

echo

while read -p "Do you want to make defconfig (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		make $defconfig
		echo
		echo "Done"
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

echo

DATE_START=$(date +"%s")

while read -p "Do you want to build (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		make -j$jobs
		echo
		echo "Done"
		cp arch/arm/boot/"$kerneltype" out
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done


if [ -f out/"$kerneltype" ]; then
	echo "Making dt.img..."
	echo
	./dtbToolCM -2 -o out/dt.img -s 2048 -p scripts/dtc/ arch/arm/boot/
	echo "dt.img created"
else
	echo "No build found..."
	exit 0;
fi

echo

if [ -f out/"$kerneltype" ]; then
	echo "Making boot.img..."
	echo
	./mkbootimg --kernel out/"$kerneltype" --ramdisk resources/initramfs.img --cmdline "$cmdline" --base $base --pagesize $ps --ramdisk_offset $ramdisk_offset --tags_offset $tags_offset --dt out/dt.img --output ozip/boot.img
else
	echo "No $kerneltype found..."
	exit 0;
fi

if [ -f arch/arm/boot/"$kerneltype" ]; then
	rm -rf ozip/system
	mkdir -p ozip/system/lib/modules
	find . -name "*.ko" -exec cp {} ozip/system/lib/modules \;
	cd ozip
	zip -r ../$buildname.zip .
	mv ../$buildname.zip $output
	cd ..
	rm -rf out ozip/system
	echo "Done..."
	rm -rf ozip/boot.img
else
	echo "Can't finish off zip..."
	exit 0;
fi

DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
echo "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."

